title: "iNaturalist Tool Library"
description: "Custom tools and biodiversity data resources"
theme: jekyll-theme-minimal
baseurl: ""  # leave empty if using username.github.io/repo-name
url: "https://yourusername.github.io"

# Navigation menu
nav:
  - name: "Home"
    link: "/"
  - name: "Tools"
    link: "/"
  - name: "Useful Links"
    link: "/pages/links.html"
